# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - complex

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ivankievets/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ivankievets/react-test npm test
 
      - run: docker build -t ivankievets/multi-client-10-14 ./client
      - run: docker build -t ivankievets/multi-nginx-10-14 ./nginx
      - run: docker build -t ivankievets/multi-server-10-14 ./server
      - run: docker build -t ivankievets/multi-worker-10-14 ./worker
 
      - run: docker push ivankievets/multi-client-10-14
      - run: docker push ivankievets/multi-nginx-10-14
      - run: docker push ivankievets/multi-server-10-14
      - run: docker push ivankievets/multi-worker-10-14

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'complex'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_58F91332AB7B455493F25C9D7D995795 }}